version: '3'
services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: Zbb010719!
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - mongodb

networks:
    mongodb:
        driver: bridge
