version: '3'
services:
  openresty1:
    image: openresty/openresty:alpine-fat
    container_name: openresty1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./logs:/usr/local/openresty/nginx/logs
      - ./html:/usr/local/openresty/nginx/html
      - ./lua:/usr/local/openresty/nginx/lua
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
    restart: always
networks:
  openresty1:
    driver: bridge

